-- Generated by drizzle-kit, then hand-amended for Phase 2 Slice 1.
-- BEFORE amendments (drizzle-kit output only):
--   CREATE TABLE profiles (... username check ...);
--   ALTER TABLE tasks ADD COLUMN user_id uuid;
--   CREATE UNIQUE INDEX profiles_username_unique ... WHERE username IS NOT NULL;
--   CREATE INDEX tasks_user_id_idx ON tasks (user_id);
--
-- Amendments add: auth.users FKs (no Auth-schema DDL), profiles/tasks RLS,
-- explicit privilege baselines (REVOKE ALL before every GRANT),
-- project-specific (lockdin_-prefixed) trigger/function names, an
-- updated_at trigger, a handle_new_user trigger, and an Auth-user profile
-- backfill.
--
-- Stop 2 correction (this revision):
--   - Renamed public.handle_new_user / public.set_profiles_updated_at and
--     their triggers to lockdin_-prefixed names. Generic/hosted Auth
--     objects are never touched by this migration.
--   - Switched CREATE OR REPLACE FUNCTION -> CREATE FUNCTION for both
--     functions: a name collision on first apply must fail the migration
--     loudly, not silently overwrite something already on the project.
--   - Removed every DROP TRIGGER statement, including the previous
--     (incorrect) "DROP TRIGGER IF EXISTS on_auth_user_created ON
--     auth.users" — this migration must never drop anything on auth.users,
--     under any name.
--   - Added explicit REVOKE ALL PRIVILEGES on profiles / tasks /
--     tasks_id_seq before granting back only the exact intended access,
--     instead of relying on default/table-level grants.
--   - Added REVOKE ... FROM PUBLIC/anon/authenticated for
--     lockdin_set_profiles_updated_at() (previously only handle_new_user
--     had these revokes).
--   - Normalised full_name metadata extraction so blank strings are treated
--     as absent (NULLIF(BTRIM(...), '')), not stored as empty text, in both
--     the signup trigger and the existing-user backfill.
--
-- Final Stop 2 evidence/hardening pass (this revision):
--   - Added REVOKE ALL PRIVILEGES ... FROM PUBLIC as a separate statement
--     preceding every anon/authenticated REVOKE on profiles, tasks, and
--     tasks_id_seq. Revoking from PUBLIC matters independently: any role
--     (including future roles) inherits whatever PUBLIC is granted, so a
--     stray PUBLIC grant would silently defeat the anon/authenticated
--     REVOKEs below it.
--
-- Do NOT apply until Stop 2 approval. Do NOT set tasks.user_id NOT NULL
-- until the hosted task-row audit
-- (docs/sql/phase2/phase2-pre-migration-audit.sql) decides wipe vs backfill.

CREATE TABLE "profiles" (
	"id" uuid PRIMARY KEY NOT NULL,
	"full_name" text,
	"username" text,
	"level" text,
	"exam_session" text,
	"onboarded_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "profiles_username_format" CHECK ("profiles"."username" is null or "profiles"."username" ~ '^[a-z0-9_]{3,24}$')
);
--> statement-breakpoint
ALTER TABLE "profiles"
  ADD CONSTRAINT "profiles_id_auth_users_id_fkey"
  FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "tasks" ADD COLUMN "user_id" uuid;
--> statement-breakpoint
ALTER TABLE "tasks"
  ADD CONSTRAINT "tasks_user_id_auth_users_id_fkey"
  FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
CREATE UNIQUE INDEX "profiles_username_unique" ON "profiles" USING btree ("username") WHERE "profiles"."username" is not null;
--> statement-breakpoint
CREATE INDEX "tasks_user_id_idx" ON "tasks" USING btree ("user_id");
--> statement-breakpoint

-- profiles.updated_at: server-side, not client-supplied.
-- CREATE FUNCTION, not OR REPLACE: a name collision must fail this
-- migration loudly rather than silently overwrite an existing function.
CREATE FUNCTION public.lockdin_set_profiles_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;
--> statement-breakpoint
REVOKE ALL ON FUNCTION public.lockdin_set_profiles_updated_at() FROM PUBLIC;
--> statement-breakpoint
REVOKE ALL ON FUNCTION public.lockdin_set_profiles_updated_at() FROM anon;
--> statement-breakpoint
REVOKE ALL ON FUNCTION public.lockdin_set_profiles_updated_at() FROM authenticated;
--> statement-breakpoint
CREATE TRIGGER lockdin_profiles_set_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.lockdin_set_profiles_updated_at();
--> statement-breakpoint

-- Bootstrap profile on Auth signup (no username, no onboarded_at, no
-- tasks). Blank-string metadata is treated as absent, not stored as empty
-- text, so a client sending full_name: "" does not defeat the NULL default.
CREATE FUNCTION public.lockdin_handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name)
  VALUES (
    NEW.id,
    COALESCE(
      NULLIF(BTRIM(NEW.raw_user_meta_data->>'full_name'), ''),
      NULLIF(BTRIM(NEW.raw_user_meta_data->>'name'), '')
    )
  );
  RETURN NEW;
END;
$$;
--> statement-breakpoint
REVOKE ALL ON FUNCTION public.lockdin_handle_new_user() FROM PUBLIC;
--> statement-breakpoint
REVOKE ALL ON FUNCTION public.lockdin_handle_new_user() FROM anon;
--> statement-breakpoint
REVOKE ALL ON FUNCTION public.lockdin_handle_new_user() FROM authenticated;
--> statement-breakpoint
CREATE TRIGGER lockdin_on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.lockdin_handle_new_user();
--> statement-breakpoint

-- Idempotent backfill for Auth users that predate the trigger (report only
-- counts from this, per docs/sql/phase2/phase2-post-migration-verification.sql).
-- Same blank-string normalisation as the trigger above.
INSERT INTO public.profiles (id, full_name)
SELECT
  u.id,
  COALESCE(
    NULLIF(BTRIM(u.raw_user_meta_data->>'full_name'), ''),
    NULLIF(BTRIM(u.raw_user_meta_data->>'name'), '')
  )
FROM auth.users AS u
ON CONFLICT (id) DO NOTHING;
--> statement-breakpoint

ALTER TABLE "profiles" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY "profiles_select_own" ON public.profiles
  FOR SELECT
  TO authenticated
  USING ((select auth.uid()) = id);
--> statement-breakpoint
CREATE POLICY "profiles_update_own" ON public.profiles
  FOR UPDATE
  TO authenticated
  USING ((select auth.uid()) = id)
  WITH CHECK ((select auth.uid()) = id);
--> statement-breakpoint
-- No INSERT/DELETE policies for authenticated/anon: trigger/cascade only.

-- Explicit privilege baseline: revoke everything first (PUBLIC, then the
-- specific roles), then grant back only the exact intended access. Do not
-- rely on default/table-level grants left over from table creation.
-- Revoking from PUBLIC matters independently of revoking from anon/
-- authenticated: any role (including future roles) inherits whatever is
-- granted to PUBLIC, so a PUBLIC grant would silently defeat every
-- anon/authenticated REVOKE below it.
REVOKE ALL PRIVILEGES ON TABLE public.profiles FROM PUBLIC;
--> statement-breakpoint
REVOKE ALL PRIVILEGES ON TABLE public.profiles FROM anon, authenticated;
--> statement-breakpoint
GRANT SELECT ON TABLE public.profiles TO authenticated;
--> statement-breakpoint
-- Column-level UPDATE: safe profile fields only. id, username,
-- onboarded_at, created_at, and updated_at are intentionally NOT granted to
-- authenticated — username/onboarded_at are reserved for a later reviewed
-- onboarding operation (not implemented in Slice 1); id and the timestamps
-- are never client-writable. anon gets no access to profiles at all.
GRANT UPDATE (full_name, level, exam_session) ON TABLE public.profiles TO authenticated;
--> statement-breakpoint

ALTER TABLE "tasks" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY "tasks_select_own" ON public.tasks
  FOR SELECT
  TO authenticated
  USING ((select auth.uid()) = user_id);
--> statement-breakpoint
CREATE POLICY "tasks_insert_own" ON public.tasks
  FOR INSERT
  TO authenticated
  WITH CHECK ((select auth.uid()) = user_id);
--> statement-breakpoint
CREATE POLICY "tasks_update_own" ON public.tasks
  FOR UPDATE
  TO authenticated
  USING ((select auth.uid()) = user_id)
  WITH CHECK ((select auth.uid()) = user_id);
--> statement-breakpoint
CREATE POLICY "tasks_delete_own" ON public.tasks
  FOR DELETE
  TO authenticated
  USING ((select auth.uid()) = user_id);
--> statement-breakpoint

-- Same PUBLIC-then-role revoke ordering as profiles above.
REVOKE ALL PRIVILEGES ON TABLE public.tasks FROM PUBLIC;
--> statement-breakpoint
REVOKE ALL PRIVILEGES ON TABLE public.tasks FROM anon, authenticated;
--> statement-breakpoint
REVOKE ALL PRIVILEGES ON SEQUENCE public.tasks_id_seq FROM PUBLIC;
--> statement-breakpoint
REVOKE ALL PRIVILEGES ON SEQUENCE public.tasks_id_seq FROM anon, authenticated;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.tasks TO authenticated;
--> statement-breakpoint
GRANT USAGE, SELECT ON SEQUENCE public.tasks_id_seq TO authenticated;
